### ISSUE TITLE
New version of irb may not work properly.

### ISSUE THREAD

**Issue by kojix2** [PyDataOsaka/irb_kernel#2]
Related to #1

**Comment by kozo2** [comment]
Could you tell me the version of irb that didn't work?
I want to add to the documentation that irb_kernel is not available for that irb version.

**Comment by kojix2** [comment]
Version 1.0

REPL improvement is one of the main features of Ruby 2.7.0 .
https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
https://www.ruby-lang.org/ja/news/2019/12/25/ruby-2-7-0-released/

**Comment by kozo2** [comment]
<img width="1425" alt="Screen Shot 2020-02-02 at 23 54 12" src="https://user-images.githubusercontent.com/12192/73610112-628fba00-4617-11ea-9433-f06173e5c940.png">

It seems Ruby 2.6.3 and irb 1.0.0 work well.
These are the pre-installed Ruby and irb gem (and Python3) on macOS Catalina.

**Comment by kojix2** [comment]
@kozo2 
how about the latest version?
 I mean irb 1.2.1

```
gem install irb -v 1.2.1
```

**Comment by kojix2** [comment]
You are right. 
Version 1.0 works. Version 1.1 does not work.

**Comment by kozo2** [comment]
Thank you for the information.
I found that replwrap.REPLWrapper does not work with irb 1.2.*
irb_kernel works well with irb 1.1.*

**Comment by kojix2** [comment]
Umm... irb 1.1 did not work on my computer.
Could you check if it really works on 1.1?

**Comment by kozo2** [comment]
<img width="1396" alt="Screen Shot 2020-02-03 at 0 19 11" src="https://user-images.githubusercontent.com/12192/73610466-df706300-461a-11ea-8efa-f6000d80e9af.png">

**Comment by kojix2** [comment]
Umm. 
I've tried it again and I confirmed that irb 1.1 did not work on my PC (Ubuntu. + Ruby 2.6.5)

It seems that there is still a little mystery...
Thanks.

**Comment by kozo2** [comment]
```
>>> hoge=replwrap.REPLWrapper("irb --nomultiline --simple-prompt",u">> ", None)
>>> hoge.run_command("1+2")
'1+2\r\n=> \x1b[34m\x1b[1m3\x1b[0m\r\n'
```

It seems these irb options work well for version 1.2.*.
But It looks like I need to add a little more code for decoding the result.
I created #3 . But don't expect too much.
At the moment I can not spend time on this project.

**Comment by kozo2** [comment]
@kojix2 I found a way to run irb 1.2.*
```
hoge=replwrap.REPLWrapper("irb --nocolorize --nomultiline --simple-prompt",u">> ", None)
```

**Comment by kozo2** [comment]
@kojix2 irb_kernel version 0.2.* supports irb 1.2.*
